org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.aapt2FromMavenOverride=/root/Android/Sdk/aapt2
android.suppressUnsupportedCompileSdk=35
org.gradle.warning.mode=none
org.gradle.caching=true
org.gradle.parallel=true
kotlin.incremental=true
